### PR TITLE
#1 replace jquery with react

### PR DESCRIPTION
**Pull request by masquel**
Here is the using fetch api to get medium posts and render them in react components

### CODE REVIEW

**Comment by masquel** [comment]
#1  @bluetch

**Comment by bluetch** [comment]
Hi @masquel could you help me check the error code?

`> shopeedesign@0.1.0 start /Users/ken/react/shopee.design
> node scripts/customized-config start

/Users/ken/react/shopee.design/node_modules/enhanced-resolve/lib/ModulesInDirectoriesPlugin.js:1
(function (exports, require, module, __filename, __dirname) { �
                                                              ^
SyntaxError: Invalid or unexpected token
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/ken/react/shopee.design/node_modules/react-scripts/node_modules/webpack/lib/WebpackOptionsApply.js:40:34)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! shopeedesign@0.1.0 start: `node scripts/customized-config start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the shopeedesign@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ken/.npm/_logs/2017-10-10T15_24_15_574Z-debug.log
`

**Comment by masquel** [comment]
@bluetch when do you get this error? I've tested it on windows and mac and everything is ok

**Comment by bluetch** [comment]
@masquel when I pull and merge, got this error, can't understand what's wrong ..

**Pull request merged**
